server:
  port: 8087
  
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ead-authuser
    username: postgres
    password: Gold#3366
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc: 
        lob.non-contextual-creation:true
    properties:
      hibernate:
        show-sql: true
  output:
    ansi:
      enabled: ALWAYS
logging:
  level:
    com.ead: TRACE
    root: INFO
ead:
  api:
    url:
      course: 'http://localhost:8082'